# Generated by Django 5.1.7 on 2025-08-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=200)),
                ('prenoms', models.CharField(max_length=200)),
                ('dateBirth', models.DateField()),
                ('codeClub', models.CharField(max_length=200)),
                ('pwdClub', models.CharField(max_length=200)),
            ],
        ),
    ]
