# Generated by Django 4.2.14 on 2025-09-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFoot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static_Img/')),
                ('vid', models.FileField(upload_to='static_Vid/')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubFoot.inscription')),
            ],
        ),
    ]
