# Generated by Django 4.2.14 on 2025-09-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFoot', '0002_imgvid'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static_Img/')),
            ],
        ),
        migrations.CreateModel(
            name='Vid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.FileField(upload_to='static_Vid/')),
            ],
        ),
        migrations.RenameModel(
            old_name='imgVid',
            new_name='imgVidUser',
        ),
    ]
