# Generated by Django 4.2.14 on 2025-09-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFoot', '0003_img_vid_rename_imgvid_imgviduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='img',
            name='titre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imgviduser',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imgviduser',
            name='titre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vid',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vid',
            name='titre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
