# Generated by Django 4.2.14 on 2025-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFoot', '0004_img_description_img_titre_imgviduser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='staticImg/'),
        ),
        migrations.AlterField(
            model_name='imgviduser',
            name='vid',
            field=models.FileField(upload_to='staticVid/'),
        ),
    ]
