# Generated by Django 4.2.14 on 2025-09-24 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFoot', '0005_alter_img_img_alter_imgviduser_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='img',
        ),
        migrations.RemoveField(
            model_name='vid',
            name='vid',
        ),
        migrations.AddField(
            model_name='img',
            name='image_choisie',
            field=models.CharField(choices=[('backFoot.jpg', 'backFoot.jpg'), ('backFoot1.jpg', 'backFoot1.jpg'), ('backFoot2.jpg', 'backFoot2.jpg'), ('backFoot3.jpg', 'backFoot3.jpg'), ('backFoot31.jpg', 'backFoot31.jpg'), ('backFoot311.jpg', 'backFoot311.jpg'), ('backFoot311_resultat.jpg', 'backFoot311_resultat.jpg'), ('backFoot4.jpg', 'backFoot4.jpg'), ('backFoot5.jpg', 'backFoot5.jpg'), ('backFoot6.jpg', 'backFoot6.jpg'), ('backFoot7.jpg', 'backFoot7.jpg'), ('backFoot8.jpg', 'backFoot8.jpg'), ('backFoot9.jpg', 'backFoot9.jpg'), ('BelgiumClub_2025.jpg', 'BelgiumClub_2025.jpg'), ('caption.jpg', 'caption.jpg'), ('club.jpg', 'club.jpg'), ("Images en forme de dessins animés pour le fichier SVG d'un match de footbal_20250831_184313_0000.jpg", "Images en forme de dessins animés pour le fichier SVG d'un match de footbal_20250831_184313_0000.jpg"), ('IMG-14-09-2025-WA0000.jpg', 'IMG-14-09-2025-WA0000.jpg'), ('LOGO.jpg', 'LOGO.jpg'), ('logo01.png', 'logo01.png'), ('Mons.jpg', 'Mons.jpg'), ('Mons.png', 'Mons.png'), ('Mons_002.jpg', 'Mons_002.jpg'), ('Mons_003.jpg', 'Mons_003.jpg'), ('Sans titre.png', 'Sans titre.png'), ('Screenshot_2025-08-22-18-01-07-509_com.miui.videoplayer.jpg', 'Screenshot_2025-08-22-18-01-07-509_com.miui.videoplayer.jpg'), ('Screenshot_2025-08-22-18-05-57-856_com.miui.videoplayer.jpg', 'Screenshot_2025-08-22-18-05-57-856_com.miui.videoplayer.jpg'), ('Screenshot_2025-08-22-18-06-05-067_com.miui.videoplayer.jpg', 'Screenshot_2025-08-22-18-06-05-067_com.miui.videoplayer.jpg'), ('Screenshot_2025-08-23-16-32-28-044_com.android.settings.jpg', 'Screenshot_2025-08-23-16-32-28-044_com.android.settings.jpg'), ('Screenshot_2025-08-23-16-32-43-992_com.android.settings.jpg', 'Screenshot_2025-08-23-16-32-43-992_com.android.settings.jpg'), ('Screenshot_2025-08-24-18-30-15-198_com.google.android.googlequicksearchbox.jpg', 'Screenshot_2025-08-24-18-30-15-198_com.google.android.googlequicksearchbox.jpg'), ('Screenshot_2025-08-24-18-30-23-642_com.google.android.googlequicksearchbox.jpg', 'Screenshot_2025-08-24-18-30-23-642_com.google.android.googlequicksearchbox.jpg'), ('Screenshot_2025-08-25-08-55-53-704_com.facebook.lite.jpg', 'Screenshot_2025-08-25-08-55-53-704_com.facebook.lite.jpg')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vid',
            name='video_choisie',
            field=models.CharField(choices=[('static_Vid.mp4', 'static_Vid.mp4'), ('static_Vid01.mp4', 'static_Vid01.mp4'), ('static_Vid02.mp4', 'static_Vid02.mp4'), ('static_Vidd.mp4', 'static_Vidd.mp4'), ('VID-14-09-2025-01.mp4', 'VID-14-09-2025-01.mp4'), ('VID-14-09-2025-02.mp4', 'VID-14-09-2025-02.mp4')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='imgviduser',
            name='img',
            field=models.ImageField(null=True, upload_to='mediaImage/'),
        ),
        migrations.AlterField(
            model_name='imgviduser',
            name='vid',
            field=models.FileField(null=True, upload_to='mediaVideo/'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='dateBirth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
