# Generated by Django 4.2.14 on 2025-09-26 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFoot', '0007_infomedia_alter_img_image_choisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='datePub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='imgviduser',
            name='datePub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='infomedia',
            name='datePub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inscription',
            name='datePub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vid',
            name='datePub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
