# Generated by Django 5.1.7 on 2025-10-11 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFoot', '0008_img_datepub_imgviduser_datepub_infomedia_datepub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('doc_choisie', models.CharField(choices=[], default='', max_length=200)),
                ('datePub', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='img',
            name='image_choisie',
            field=models.CharField(choices=[('backFoot.jpg', 'backFoot.jpg'), ('backFoot1.jpg', 'backFoot1.jpg'), ('backFoot2.jpg', 'backFoot2.jpg'), ('backFoot3.jpg', 'backFoot3.jpg'), ('backFoot311.jpg', 'backFoot311.jpg'), ('backFoot4.jpg', 'backFoot4.jpg'), ('backFoot5.jpg', 'backFoot5.jpg'), ('backFoot6.jpg', 'backFoot6.jpg'), ('backFoot7.jpg', 'backFoot7.jpg'), ('backFoot8.jpg', 'backFoot8.jpg'), ('backFoot9.jpg', 'backFoot9.jpg'), ('BelgiumClub_2025.jpg', 'BelgiumClub_2025.jpg'), ('caption.jpg', 'caption.jpg'), ('club.jpg', 'club.jpg'), ('image.png', 'image.png'), ("Images en forme de dessins animés pour le fichier SVG d'un match de footbal_20250831_184313_0000.jpg", "Images en forme de dessins animés pour le fichier SVG d'un match de footbal_20250831_184313_0000.jpg"), ('IMG-14-09-2025-WA0000.jpg', 'IMG-14-09-2025-WA0000.jpg'), ('LOGO.jpg', 'LOGO.jpg'), ('logo01.png', 'logo01.png'), ('Mons.jpg', 'Mons.jpg'), ('Mons.png', 'Mons.png'), ('mons1a.jpg', 'mons1a.jpg'), ('mons1b.jpg', 'mons1b.jpg'), ('mons1c.jpg', 'mons1c.jpg'), ('mons1d.jpg', 'mons1d.jpg'), ('Sans titre.png', 'Sans titre.png'), ('images.jpg', 'images.jpg'), ('images.png', 'images.png'), ('images (1).jpg', 'images (1).jpg'), ('imageS2.png', 'imageS2.png'), ('header.jpg', 'header.jpg'), ('header2.jpg', 'header2.jpg'), ('header3.jpg', 'header3.jpg'), ('header4.jpg', 'header4.jpg'), ('header5.jpg', 'header5.jpg'), ('header6.jpg', 'header6.jpg'), ('header7.jpg', 'header7.jpg'), ('player.jpg', 'player.jpg'), ('playeR.png', 'playeR.png'), ('imgVeteran1.jpg', 'imgVeteran1.jpg'), ('header8.jpg', 'header8.jpg')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vid',
            name='video_choisie',
            field=models.CharField(choices=[('static_Vid.mp4', 'static_Vid.mp4'), ('static_Vid01.mp4', 'static_Vid01.mp4'), ('static_Vid02.mp4', 'static_Vid02.mp4'), ('static_Vidd.mp4', 'static_Vidd.mp4'), ('VID-14-09-2025-01.mp4', 'VID-14-09-2025-01.mp4'), ('VID-14-09-2025-02.mp4', 'VID-14-09-2025-02.mp4'), ('Apprendre_CSS_GRID_-_Le_tuto_pour_enfin_comprendre_les_grilles_CSS(480p).mp4', 'Apprendre_CSS_GRID_-_Le_tuto_pour_enfin_comprendre_les_grilles_CSS(480p).mp4')], default='', max_length=200),
        ),
    ]
