# Generated by Django 5.1.7 on 2025-10-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFoot', '0009_doc_alter_img_image_choisie_alter_vid_video_choisie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='doc_choisie',
            field=models.CharField(choices=[('cours-sql-sh-.pdf', 'cours-sql-sh-.pdf'), ('pyinstaller.pdf', 'pyinstaller.pdf'), ('pyinstaller-org-en-v3.3.pdf', 'pyinstaller-org-en-v3.3.pdf'), ('DevMeetup-Eel-20190122.pdf', 'DevMeetup-Eel-20190122.pdf')], default='', max_length=200),
        ),
    ]
